# HelmCharts/postgresql/tablespaces/config.yaml
primary:
  extendedConfiguration: |
    CREATE TABLESPACE ts_chimera_meta LOCATION '/var/lib/postgresql/tablespaces/ts_chimera_meta';
    CREATE TABLESPACE ts_chimera_data LOCATION '/var/lib/postgresql/tablespaces/ts_chimera_data';
    CREATE TABLESPACE ts_chimera_index LOCATION '/var/lib/postgresql/tablespaces/ts_chimera_index';
    CREATE TABLESPACE ts_chimera_temp LOCATION '/var/lib/postgresql/tablespaces/ts_chimera_temp';
    CREATE TABLESPACE ts_chimera_wal LOCATION '/var/lib/postgresql/tablespaces/ts_chimera_wal';
    CREATE TABLESPACE ts_chimera_dh LOCATION '/var/lib/postgresql/tablespaces/ts_chimera_dh';
  extraVolumes:
    - name: ts-chimera-meta
      persistentVolumeClaim:
        claimName: ts-chimera-meta-pvc
    - name: ts-chimera-data
      persistentVolumeClaim:
        claimName: ts-chimera-data-pvc
    - name: ts-chimera-index
      persistentVolumeClaim:
        claimName: ts-chimera-index-pvc
    - name: ts-chimera-temp
      persistentVolumeClaim:
        claimName: ts-chimera-temp-pvc
    - name: ts-chimera-wal
      persistentVolumeClaim:
        claimName: ts-chimera-wal-pvc
    - name: ts-chimera-dh
      persistentVolumeClaim:
        claimName: ts-chimera-dh-pvc
  extraVolumeMounts:
    - name: ts-chimera-meta
      mountPath: /var/lib/postgresql/tablespaces/ts_chimera_meta
    - name: ts-chimera-data
      mountPath: /var/lib/postgresql/tablespaces/ts_chimera_data
    - name: ts-chimera-index
      mountPath: /var/lib/postgresql/tablespaces/ts_chimera_index
    - name: ts-chimera-temp
      mountPath: /var/lib/postgresql/tablespaces/ts_chimera_temp
    - name: ts-chimera-wal
      mountPath: /var/lib/postgresql/tablespaces/ts_chimera_wal
    - name: ts-chimera-dh
      mountPath: /var/lib/postgresql/tablespaces/ts_chimera_dh