apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
#   annotations:
#     helm.sh/hook: "pre-install,pre-upgrade"  # Auto-run on install/upgrade
#     helm.sh/hook-delete-policy: "before-creation"  # Clean up previous jobs
spec:
  template:
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
      - name: run-sql
        image: {{ .Values.job.image }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            # Using connection URI hides password from process list
            psql "postgresql://{{ .Values.db.username }}:{{ .Values.db.password }}@{{ .Values.db.host }}:{{ .Values.db.port }}/postgres" \
                 -f /sql/init.sql
        volumeMounts:
          - name: sql-scripts
            mountPath: /sql
      volumes:
        - name: sql-scripts
          configMap:
            name: {{ .Release.Name }}-sql-queries