apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  app.js: |
    const express = require('express');
    const app = express();
    const port = 3000;

    app.get('/', (req, res) => {
      const user = req.headers['authorization'] ? 'Authenticated User' : 'Guest';
      res.send(`
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>{{ .Values.portal.title }}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            h1 { color: #333; }
            table { border-collapse: collapse; width: 100%; max-width: 1200px; }
            th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
            th { background-color: #f2f2f2; }
            a { color: #0066cc; text-decoration: none; }
            a:hover { text-decoration: underline; }
            .action-btn { padding: 5px 10px; background-color: #4CAF50; color: white; border: none; cursor: pointer; }
            .action-btn:hover { background-color: #45a049; }
          </style>
        </head>
        <body>
          <h1>{{ .Values.portal.title }}</h1>
          <p>Welcome, ${user}!</p>
          <table>
            <tr>
              <th>Service</th>
              <th>URL</th>
              <th>Username</th>
              <th>Description</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
            {{- range .Values.portal.services }}
            <tr>
              <td>{{ .name }}</td>
              <td><a href="{{ .url }}" target="_blank">{{ .url }}</a></td>
              <td>{{ .username }}</td>
              <td>{{ .description }}</td>
              <td>{{ .status }}</td>
              <td>
                {{- if eq .name "ArgoCD" }}
                <button class="action-btn" onclick="alert('Sync not implemented')">Sync Data App</button>
                {{- else if eq .name "GitLab" }}
                <button class="action-btn" onclick="alert('Trigger not implemented')">Run Data Pipeline</button>
                {{- else }}
                <span>N/A</span>
                {{- end }}
              </td>
            </tr>
            {{- end }}
          </table>
          <p>Add more data platform services in values.yaml as needed.</p>
        </body>
        </html>
      `);
    });

    app.listen(port, () => {
      console.log(`Server running at http://localhost:${port}`);
    });
  package.json: |
    {
      "name": "chimera-infra",
      "version": "1.0.0",
      "dependencies": {
        "express": "^4.17.1"
      }
    }