{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range .Values.portal.services }}
  {{ .name | lower | replace " " "-" }}-username: {{ .username | b64enc | quote }}
  {{- end }}
{{- end }}