replicaCount: 1
image:
  repository: python
  tag: "3.10"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 8080
resources:
  requests:
    cpu: "0.5"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"
ollamaUrl: "http://ollama.default.svc.cluster.local:11434"
model: "phi3"
