# values-dev.yaml
namespace: dev-apisix  # Set the namespace for all components
installCRDs: true 
apisix:
  enabled: true
  replicaCount: 1
  

dashboard:
  enabled: true
  replicaCount: 1
  service:
    type: NodePort

ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: dev-apisix  # Ensure the Ingress Controller points to the correct namespace
plugins:
  enabled:
    - openid-connect