global:
  enabled: true
  name: vault

# Enable HA mode with Raft as the storage backend
server:
  securityContext:
    readOnlyRootFilesystem: false
  extraEnvironmentVars:
    VAULT_CONFIG_DIR: /vault/config
    VAULT_ADDR: "http://0.0.0.0:8200"
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: openebs-hostpath
    accessMode: ReadWriteOnce
  ha:
    enabled: true
    replicas: 1
    raft:
      enabled: true
  # Raft configuration
  storage:
    raft:
      enabled: true
      path: /vault/data
  # Configure the Vault service and the pod labels
  service:
    enabled: true
    name: vault
    port: 8200
  ingress:
    enabled: false
  unsealing:
    # Disable auto unsealing, which will require manual unsealing
    auto_unseal: false

# Set values to allow for manual unsealing
ui:
  enabled: true

# Configuring Vault to use root token for manual unsealing (unseal with root token)
vault:
  unseal:
    enabled: true

