image:
  repository: kennethreitz/httpbin
  tag: latest
replicaCount: 3
service:
  type: NodePort
  port: 80
  nodePort: 30082  # http://46.202.163.54:30082
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"