apiVersion: v1
kind: Service
metadata:
  name: httpbin-api
  namespace: httpbin-namespace
spec:
  selector:
    app: httpbin-api
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}