apiVersion: v1
kind: Secret
metadata:
  name: api-service-repo-secret
  namespace: dev-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: api-service
  type: helm
  url: ghcr.io/panthers-labs-pvt-ltd/synterra
  username: panthers-labs-pvt-ltd
  password: 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
  enableOCI: "true"
