apiVersion: v1
kind: Secret
metadata:
  name: ghcr-helm-repo
  namespace: dev-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: ghcr-helm
  url: oci://ghcr.io/eeswarareddy
  password: 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
  username: eeswarareddy
