apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-master-keycloak
  namespace: default
  annotations:
    nginx.org/mergeable-ingress-type: master
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostname }}  # Dynamic hostname from values
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: pantherslabs-tls