apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-minion-keycloak
  namespace: dev-keycloak
  annotations:
    nginx.org/mergeable-ingress-type: minion
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-http
            port:
              number: 8080